name: Build and Dev Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-dev-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: true
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Check TypeScript compilation
        run: |
          # 检查 TypeScript 编译是否成功
          npx tsc --noEmit && echo "TypeScript compilation successful"

      - name: Check build command
        run: pnpm run build

      - name: Lint check
        run: pnpm run lint
        continue-on-error: true  # 由于我们暂时禁用了 ESLint，这个步骤可能会失败，但不会阻止构建

      - name: Check dev command (compile only)
        run: |
          # 只检查编译是否成功，不需要启动服务器
          pnpm run build && echo "Dev compilation successful" 